---
  - name: "Installing OS cluster"
    hosts: localhost
    connection: local
    vars_files:
      - /home/ubuntu/vars 

    tasks:
      - name: Execute common tasks
        ansible.builtin.include_tasks: tasks/01-common-prereq-tasks.yaml

      - name: Add IAM tags for AWS
        ansible.builtin.include_tasks: tasks/01.a-aws-prereq-tasks.yaml
        when: provider == 'aws'

      - name: Provisioning cluster
        ansible.builtin.include_tasks: tasks/02-installation-task.yaml

      - name: Upload Terraform and metadata files to S3
        ansible.builtin.include_tasks: tasks/upload-to-s3-task.yaml

      - name: "labelling nodes"
        ansible.builtin.include_tasks: tasks/label-nodes.yaml
        with_items:
          - "control-plane"
          - "worker"

      - name: Deleting files from Ansible controller
        ansible.builtin.include_tasks: tasks/cleanup.yaml
        vars: "{{ cluster_name }}"
