- name: Creating S3 bucket if not present
  amazon.aws.s3_bucket:
    name: "{{ bucket_name }}"
    region: "{{ bucket_region }}"
    state: present
          #      ignore_errors: true  #continues if creation fails due to existing bucket

          #   - name: Debug Bucket Creation
          #      debug:
          #        var: bucket

- name: Copying files to S3
  community.aws.s3_sync:
    bucket: "{{ bucket_name }}"
    file_root: "{{ cluster_name }}/{{ provider }}/"
    key_prefix: "{{ provider }}/{{ cluster_name }}/"
  register: s3

- name: Debug S3 Sync
  debug:
    var: s3
#  when: "'aws' in provider or 'azure' in provider" 
