- name: Remove folder form controller machine
  ansible.builtin.file:
    path: "{{ cluster_name }}"
    state: absent
  register: outputd
  changed_when: outputd.changed

- name: Debugging output
  debug:
    var: outputd
