---
    - name: Cloning repo for install-config template
      ansible.builtin.git:
        repo: https://github.com/AnuThac/os-cluster-provisioning.git
        dest: '{{ cluster_name }}'
        version: main

    - name: Installing AWS cli
      become: true
      shell: |
        apt install unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip
      when: provider == "aws"


    - name: Installing  CLIs- oc, kubectl
      become: true
      shell: |
        wget -q https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar zxvf openshift-client-linux.tar.gz
        chmod 777 /usr/local/bin/oc
        chmod 777 /usr/local/bin/kubectl
        sudo cp oc /usr/local/sbin/
        sudo cp kubectl /usr/local/sbin/
        rm -rf openshift-client-linux.tar.gz
      register: "cli"
    - debug: var=cli.stdout_lines

    - name: Updating Install config file
      template:
        src: '{{ cluster_name }}/{{ provider }}/install-config.j2'
        dest: '{{ cluster_name }}/{{ provider }}/install-config.yaml'

    - name: Downloading Openshift Installer
      become: true
      shell: |
        wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
        tar -xvzf openshift-install-linux.tar.gz
        cp openshift-install /usr/local/bin/
        rm -rf openshift-install-linux.tar.gz*
      register: "installer"
    - debug: var=installer.stdout.lines

