- name: "labelling nodes"
  hosts: localhost
  connection: local
  vars_files:
  - /home/ubuntu/testing/tags-vars

  tasks:
    - name: "copying kubeconfig file and connecting to cluster"
      shell: |
        aws s3 cp 's3://openshift-ansible/{{ provider }}/{{ cluster_name }}/auth/kubeconfig' '{{ cluster_name }}'

    - name: "labelling master nodes"
      block:
        - name: "get master nodes"
          shell: |
            export KUBECONFIG={{ cluster_name }}
            oc get nodes -l node-role.kubernetes.io/control-plane -o custom-columns=NAME:.metadata.name --no-headers=true
          register: "master_nodelist"

        - name: "label master nodes"
          shell: |
            export KUBECONFIG='{{ cluster_name }}/kubeconfig'
            oc label node {{ item }} {{ master_tags }} --overwrite
          with_items:
            - "{{ master_nodelist.stdout_lines }}"
      when: lookup('vars', 'master_tags', default="") != ""

    - name: "labelling worker nodes"
      block:
        - name: "get worker nodes"
          shell: |
            export KUBECONFIG='{{ cluster_name }}'
            oc get nodes -l node-role.kubernetes.io/worker= -o custom-columns=NAME:.metadata.name --no-headers=true
          register: "worker_nodelist"

        - name: "label worker nodes"
          shell: |
            export KUBECONFIG='{{ cluster_name }}/kubeconfig'
            oc label node {{ item }} {{ worker_tags }} --overwrite
          with_items:
            - "{{ worker_nodelist.stdout_lines }}"
      when: lookup('vars', 'worker_tags', default="") != ""

