---
#    - name: "reformatting labels"
#      ansible.builtin.shell: |
#        echo {{ label.key }}={{ label.value }}
#      loop: {{ item | items2dict }}
#      loop_control:
#        loop_var: label
#      register: labels
#
#    - debug:
#        msg: "{{ labels.stdout }}"

    - name: "labelling nodes"
      block:
        - name: "get nodes"
          shell: |
            oc get nodes -l node-role.kubernetes.io/{{ item if (item != 'worker') else 'worker=' }} -o custom-columns=NAME:.metadata.name --no-headers=true
          register: "nodelist"
       
        - name: "label nodes"
          shell: |
            oc label node {{ node_name }} {{ node_label }}
          loop: "{{ nodelist.stdout_lines }}"
          loop_control:
            loop_var: node_name

      when: vars[node_type] is defined and vars[node_type] is truthy
      vars:
        node_type: "{{ item | replace('-', '_') }}"
        node_label: "{{ lookup('vars', node_type) }}"
      rescue:
        - name: "update label nodes"
          when: ansible_failed_task.name == "label nodes"
          shell: |
            oc label node {{ node_name }} {{ node_label }} --overwrite
          loop: "{{ nodelist.stdout_lines }}"
          loop_control:
            loop_var: node_name

